role: postfix: change postfix__relayhost_username to optional
Linuxfabrik/lfops pull request #133
Opened 2023-11-23 13:56 UTC by lfchris

2023-11-23 17:19 UTC, NavidSassan commented on roles/postfix/tasks/main.yml
> +        line: '{{ (postfix__smtp_sasl_security_options is defined and postfix__smtp_sasl_security_options | length) | ternary("smtp_sasl_security_options = " + postfix__smtp_sasl_security_options, "#
why are you checking if it is defined? empty string is not one of the possible options in the README.

2023-11-23 17:19 UTC, NavidSassan commented on roles/postfix/README.md
> +| `postfix__smtp_sasl_security_options` | Postfix SMTP client SASL security options. Possible options:<br>* `noplaintext`<br>* `noactive`<br>* `nodictionary`<br>* `noanonymous`<br>* `mutual_auth` | `
according to https://www.postfix.org/postconf.5.html it is a list of options. should we also make it a list?

2023-11-23 17:19 UTC, NavidSassan commented on roles/postfix/README.md
> +| `postfix__smtp_sasl_security_options` | Postfix SMTP client SASL security options. Possible options:<br>* `noplaintext`<br>* `noactive`<br>* `nodictionary`<br>* `noanonymous`<br>* `mutual_auth` | `
also, why are we setting the default to `noanonymous`?

2023-11-28 09:09 UTC, NavidSassan requested changes

2023-11-28 09:09 UTC, NavidSassan commented on roles/postfix/README.md
> +| `postfix__smtp_sasl_security_options` | Postfix SMTP client SASL security options, separated by commas. Possible options:<br>* `noplaintext`<br>* `noactive`<br>* `nodictionary`<br>* `noanonymous`<b
"List of ..."

2023-11-28 09:09 UTC, NavidSassan commented on roles/postfix/README.md
> +| `postfix__smtp_sasl_security_options` | Postfix SMTP client SASL security options, separated by commas. Possible options:<br>* `noplaintext`<br>* `noactive`<br>* `nodictionary`<br>* `noanonymous`<b
and the default should be a compact list: `['noanonymous', 'noplaintext']`

2023-11-28 09:09 UTC, NavidSassan commented on roles/postfix/tasks/main.yml
> +        line: '{{ postfix__smtp_sasl_security_options | length | ternary("smtp_sasl_security_options = " + postfix__smtp_sasl_security_options | default(["noplaintext", "noanonymous"]) | join(", "),
no ternary required anymore, as we have a default in the defaults/main.yml.

2023-11-28 09:36 UTC, lfchris commented on roles/postfix/tasks/main.yml
> +        line: '{{ postfix__smtp_sasl_security_options | length | ternary("smtp_sasl_security_options = " + postfix__smtp_sasl_security_options | default(["noplaintext", "noanonymous"]) | join(", "),
Ternary is needed because of the possibility of setting `postfix__smtp_sasl_security_options` to an empty array, which should lead to the following: `smtp_sasl_security_options =`

2023-11-28 09:43 UTC, merged