Feature/role grafana improvements
Linuxfabrik/lfops pull request #144
Opened 2024-03-06 09:39 UTC by paasi6666

- added optional `grafana__smtp_config`
- added optional `grafana__https_config`
- added `ssl_skip_verify` for ldap config
- fixed attribute username in ldap config
- fixed quotation for grafana admin reset (to use more complex passwords)

2024-03-14 16:41 UTC, NavidSassan requested changes
thanks for your contributions :D

2024-03-14 16:42 UTC, NavidSassan commented
please let me know if keeping the `attribute_username` and `attribute_email` variables works for you, then I can adjust and merge

2024-03-19 08:16 UTC, paasi6666 commented on roles/grafana/templates/etc/grafana/ldap.toml.j2
> +email =  "{{ grafana__ldap_config.email | default('email') }}"
Makes perfect sense. Thanks!

2024-03-19 08:17 UTC, paasi6666 reviewed
Makes perfect sense. Thanks!

2024-03-19 08:20 UTC, paasi6666 commented
> please let me know if keeping the `attribute_username` and `attribute_email` variables works for you, then I can adjust and merge

Still works after changing the `attribute_username` and `attribute_email` variables.

2024-03-19 16:12 UTC, merged