Feature/graylog server
Linuxfabrik/lfops pull request #92
Opened 2022-10-14 12:02 UTC by lfchris

2022-10-24 08:19 UTC, NavidSassan requested changes

2022-10-24 08:19 UTC, NavidSassan commented on playbooks/setup_graylog.yml
> +    - 'lfops_setup_graylog'
same for all the variables of course

2022-10-24 08:19 UTC, NavidSassan commented on playbooks/setup_graylog.yml
> +      opensearch__version__dependent_var:
same as the comment for the other version above

2022-10-24 08:19 UTC, NavidSassan commented on roles/graylog_server/README.md
> +You can choose between `opensearch` (default) and `elasticsearch` as searchengine. If you choose to use `opensearch`, Graylog Server 4.3 is required!
```suggestion
You can choose between `opensearch` (default) and `elasticsearch` as the searchengine. If you choose to use `opensearch`, Graylog Server 4.3 is required!
```

2022-10-24 08:19 UTC, NavidSassan commented on roles/graylog_server/README.md
> +* Enable the official [Graylog repository](https://docs.graylog.org/docs/centos). This can be done using the [linuxfabrik.lfops.repo_graylog](https://github.com/Linuxfabrik/lfops/tree/main/roles/repo
and java, mongodb, a searchengine, etc?

2022-10-24 08:19 UTC, NavidSassan commented on roles/graylog_server/README.md
> +
```suggestion
If you use the ["Setup Graylog Server" Playbook](https://github.com/Linuxfabrik/lfops/blob/main/playbooks/setup_graylog_server.yml), this is automatically done for you.

```

2022-10-24 08:19 UTC, NavidSassan commented on roles/graylog_server/README.md
> +| `graylog_server:state`  | Manages the state of the graylog Server service |
```suggestion
| `graylog_server:state`  | Manages the state of the Graylog Server service |
```

2022-10-24 08:19 UTC, NavidSassan commented on roles/graylog_server/README.md
> +| Variable | Description | Default Value |
no default value column

2022-10-24 08:19 UTC, NavidSassan commented on roles/graylog_server/README.md
> +| `graylog_server__root_password` | The password which sould be set for the admin user. | unset |
why root instead of admin? is that the default username? if yes, mention it in the description here

2022-10-24 08:19 UTC, NavidSassan commented on roles/graylog_server/README.md
> +| `graylog_server__install_plugins` | Whether following plugins sould be installed additionally: `graylog-enterprise-plugins`, `graylog-integrations-plugins` and `graylog-enterprise-integrations-plug
this should be a list of optional plugins (like the modules in the php role), not a bool

2022-10-24 08:19 UTC, NavidSassan commented on roles/graylog_server/README.md
> +| `graylog_server__root_username` | The admin username which should be used. | `'admin'` |
this should be a `graylog_server__admin_user` with `username` and `password` subkey. of course this would be mandatory then. have a look at the mariadb_server role

2022-10-24 08:19 UTC, NavidSassan commented on roles/graylog_server/README.md
> +| `graylog_server__root_email` | The email address of the root user. | `''` |
admin instead of root

2022-10-24 08:19 UTC, NavidSassan commented on roles/graylog_server/README.md
> +| `graylog_server__timezone` | The time zone setting of the root user. See [joda.org](http://www.joda.org/joda-time/timezones.html) for a list of valid time zones. | `'UTC'` |
shouldn't we default to zurich?

2022-10-24 08:19 UTC, NavidSassan commented on roles/graylog_server/README.md
> +| `graylog_server__service_enabled` | Enable or disable the Graylog Server Service | `true` |
we had a default description for this, use that one please

2022-10-24 08:19 UTC, NavidSassan commented on roles/graylog_server/README.md
> +# mandatory
the mandatory example should be below the mandatory variables, not here

2022-10-24 08:19 UTC, NavidSassan commented on roles/graylog_server/README.md
> +graylog_server__http_bind_address: '192.168.1.10'
use a rfc5737 compliant example ip, see the contributing

2022-10-24 08:19 UTC, NavidSassan commented on roles/graylog_server/README.md
> +| `graylog_server__http_bind_address` | The network interface used by the Graylog HTTP interface. | `'127.0.0.1'` |
missing in the defaults file

2022-10-24 08:19 UTC, NavidSassan commented on roles/graylog_server/README.md
> +| `graylog_server__http_bind_port` | The port used by the Graylog HTTP interface. | `9000` |
same here

2022-10-24 08:19 UTC, NavidSassan commented on roles/graylog_server/defaults/main.yml
> +graylog_server__elasticsearch_oss__action_auto_create_index__dependent_var: 'false'
should be bool

2022-10-24 08:19 UTC, NavidSassan commented on roles/graylog_server/defaults/main.yml
> +graylog_server__opensearch__action_auto_create_index__dependent_var: 'false'
should be bool

2022-10-24 08:19 UTC, NavidSassan commented on roles/graylog_server/tasks/main.yml
> +  - name: "Install Graylog Server"
should be the actual package name

2022-10-24 08:19 UTC, NavidSassan commented on roles/graylog_server/tasks/main.yml
> +  - name: 'Set httpd_can_network_connect flag on and keep it persistent across reboots'
inject this to the selinux role

2022-10-24 08:19 UTC, NavidSassan commented on roles/graylog_server/tasks/main.yml
> +  - name: 'Set "cluster.name" setting for Elasticsearch'
do not do this here - should be injected

2022-10-24 08:19 UTC, NavidSassan commented on roles/repo_graylog/defaults/main.yml
> +repo_graylog__version: '4.3'
this is a mandatory variable - shouldn't have a default

2022-10-27 10:04 UTC, lfchris commented on playbooks/graylog_server.yml
> +- name: 'Install and configure Graylog Server'
But what if there is an already setup environment? We would like to be able to install only Graylog on top of it.

2022-10-27 13:05 UTC, NavidSassan commented on playbooks/graylog_server.yml
> +- name: 'Install and configure Graylog Server'
then you can use the `skip` vars. not the most elegant, but a rare use-case anyway

2022-10-27 13:40 UTC, NavidSassan requested changes
make sure to have a look at all the comments please (the github gui sometimes hides them). also, please remember to add this to the new `playbooks/all.yml` after merging

2022-10-27 13:40 UTC, NavidSassan commented on playbooks/setup_graylog_server.yml
> +        - 'not setup_graylog__skip_elasticsearch_oss | default(true)'
```suggestion
        - 'not setup_graylog__skip_repo_elasticsearch_oss | default(true)'
```

2022-10-27 13:40 UTC, NavidSassan commented on playbooks/setup_graylog_server.yml
> +        - 'setup_graylog__skip_opensearch | default(false)'
i would not do this - just set sensible defaults, rest is the responsibility of the admin. doing this would get confusing, since this variable should be called `setup_graylog__skip_repo_opensearch`, `setup_graylog__skip_opensearch` is for the `opensearch` role itself

2022-10-27 13:40 UTC, NavidSassan commented on playbooks/setup_graylog_server.yml
> +        - 'not graylog__skip_repo_graylog | d(false)'
wrong variabe name

2022-10-27 13:40 UTC, NavidSassan commented on playbooks/setup_graylog_server.yml
> +        - 'setup_graylog__skip_opensearch | default(false)'
same as problem above

2022-10-27 13:40 UTC, NavidSassan commented on roles/graylog_server/README.md
> +You can choose between `opensearch` (default) and `elasticsearch` as searchengine. If you choose to use `opensearch`, Graylog Server 4.3 is required!
still open

2022-10-27 13:40 UTC, NavidSassan commented on roles/graylog_server/tasks/main.yml
> +  - name: "install graylog server"
```suggestion
  - name: "install graylog-server"
```

2022-10-27 13:40 UTC, NavidSassan commented on roles/graylog_server/tasks/main.yml
> +      src: 'etc/graylog/server/server-{{ repo_graylog__version }}.conf.j2'
do not use `repo_graylog__version` here, since this role should work without the `repo_graylog` role. check out how the php role detects the currently installed version

2022-10-27 13:40 UTC, NavidSassan commented on playbooks/setup_graylog.yml
> +    - role: 'linuxfabrik.lfops.repo_mongodb'
still open

2022-10-27 13:40 UTC, NavidSassan commented on playbooks/setup_graylog.yml
> +    - role: 'linuxfabrik.lfops.java'
still open

2022-10-27 13:40 UTC, NavidSassan commented on playbooks/setup_graylog.yml
> +    - role: 'linuxfabrik.lfops.mongodb'
still open

2022-10-27 13:40 UTC, NavidSassan commented on playbooks/setup_graylog.yml
> +        - 'not setup_graylog__skip_elasticsearch_oss | default(true)'
still open

2022-10-27 13:40 UTC, NavidSassan commented on roles/graylog_server/README.md
> +* Enable the official [Graylog repository](https://docs.graylog.org/docs/centos). This can be done using the [linuxfabrik.lfops.repo_graylog](https://github.com/Linuxfabrik/lfops/tree/main/roles/repo
still open

2022-10-27 13:40 UTC, NavidSassan commented on roles/graylog_server/README.md
> +
still open

2022-10-27 13:40 UTC, NavidSassan commented on roles/graylog_server/README.md
> +| `graylog_server:state`  | Manages the state of the graylog Server service |
still open

2022-10-27 13:40 UTC, NavidSassan commented on roles/graylog_server/README.md
> +| Variable | Description | Default Value |
still open

2022-10-27 13:40 UTC, NavidSassan commented on roles/graylog_server/README.md
> +| `graylog_server__install_plugins` | Whether following plugins sould be installed additionally: `graylog-enterprise-plugins`, `graylog-integrations-plugins` and `graylog-enterprise-integrations-plug
still open

2022-10-27 13:40 UTC, NavidSassan commented on roles/graylog_server/README.md
> +| `graylog_server__root_username` | The admin username which should be used. | `'admin'` |
still open

2022-10-27 13:40 UTC, NavidSassan commented on roles/graylog_server/README.md
> +| `graylog_server__timezone` | The time zone setting of the root user. See [joda.org](http://www.joda.org/joda-time/timezones.html) for a list of valid time zones. | `'UTC'` |
still open

2022-10-27 13:40 UTC, NavidSassan commented on roles/graylog_server/README.md
> +graylog_server__http_bind_address: '192.168.1.10'
still open

2022-10-27 13:40 UTC, NavidSassan commented on roles/graylog_server/README.md
> +| `graylog_server__http_bind_address` | The network interface used by the Graylog HTTP interface. | `'127.0.0.1'` |
still open

2022-10-27 13:40 UTC, NavidSassan commented on roles/graylog_server/README.md
> +| `graylog_server__http_bind_port` | The port used by the Graylog HTTP interface. | `9000` |
still open

2022-10-27 13:40 UTC, NavidSassan commented on roles/graylog_server/tasks/main.yml
> +  - name: 'Set httpd_can_network_connect flag on and keep it persistent across reboots'
still open

2022-10-27 13:40 UTC, NavidSassan commented on roles/graylog_server/README.md
> +| `graylog_server__root_email` | The email address of the root user. | `''` |
still open

2022-10-27 13:40 UTC, NavidSassan commented on roles/graylog_server/README.md
> +| `graylog_server__service_enabled` | Enable or disable the Graylog Server Service | `true` |
still open

2022-10-28 08:52 UTC, NavidSassan commented on roles/graylog_server/README.md
> +graylog_server__http_bind_address: '192.168.1.10'
yes, use an address from one of those subnets

2022-10-28 13:47 UTC, NavidSassan requested changes
looks pretty good

2022-10-28 13:47 UTC, NavidSassan commented on roles/graylog_server/README.md
>  graylog_server__root_username: 'graylog-admin'
old variable

2022-10-28 13:47 UTC, NavidSassan commented on roles/graylog_server/README.md
>  graylog_server__root_email: 'webmaster@example.com'
old variable

2022-10-28 13:47 UTC, NavidSassan commented on roles/graylog_server/tasks/main.yml
> +      graylog__installed_version: '{{ ansible_facts["packages"]["graylog-server"][0]["version"] | regex_replace("\.\d+$", "") }}'
```suggestion
      graylog_server__installed_version: '{{ ansible_facts["packages"]["graylog-server"][0]["version"] | regex_replace("\.\d+$", "") }}'
```

2022-10-28 13:47 UTC, NavidSassan commented on roles/graylog_server/templates/etc/graylog/server/server-4.0.conf.j2
> +root_username = {{ graylog_server__admin_user["username"] | default('admin') }}
mention this default in the readme, or remove it

2022-10-28 13:47 UTC, NavidSassan commented on roles/graylog_server/templates/etc/graylog/server/server-4.0.conf.j2
> +root_email = {{ graylog_server__admin_user["email"] | default('') }}
mention this default in the readme, or remove it

2022-10-28 13:47 UTC, NavidSassan commented on roles/graylog_server/tasks/main.yml
> +  - name: "install graylog-server"
just for consistency :)
```suggestion
  - name: 'install graylog-server'
```

2022-10-28 13:47 UTC, NavidSassan commented on roles/graylog_server/tasks/main.yml
>    - name: "install graylog server plugins"
```suggestion
  - name: 'install graylog server plugins'
```

2022-10-28 13:47 UTC, NavidSassan commented on roles/graylog_server/defaults/main.yml
> +graylog_server__http_bind_port: '9000'
```suggestion
graylog_server__http_bind_port: 9000
```

2022-10-28 13:47 UTC, NavidSassan commented on roles/graylog_server/README.md
> +| `graylog_server__plugins` | A list of available plugins which can be installed additionally: </br> * `graylog-enterprise-plugins`<br/> * `graylog-integrations-plugins`<br/> *  `graylog-enterprise-i
```suggestion
| `graylog_server__plugins` | A list of available plugins which can be installed additionally. Possible options: </br> * `graylog-enterprise-plugins`<br/> * `graylog-integrations-plugins`<br/> *  `graylog-enterprise-integrations-plugins` | `[]` |
```

2022-10-28 13:47 UTC, NavidSassan commented on roles/graylog_server/README.md
> +| `graylog_server__admin_user` | The main user account for the graylog administrator. Subkeys:<br> * `username`: Username<br> * `password`: Password<br> * `email`: Email<br> |
Something like:
```suggestion
| `graylog_server__admin_user` | The main user account for the graylog administrator. Subkeys:<br> * `username`: Optional, string. Username. Defaults to `'admin'`. <br> * `password`: Mandatory, string. Password. <br> * `email`: Optional, string. Email. Defaults to `''`.  |
```

2022-10-28 14:34 UTC, NavidSassan commented on roles/graylog_server/README.md
> +| `graylog_server__admin_user` | The main user account for the graylog administrator. Subkeys:<br> * `username`: Username<br> * `password`: Password<br> * `email`: Email<br> |
please use this notation to be consistent with the other readmes

2022-10-28 14:39 UTC, NavidSassan commented on roles/graylog_server/README.md
> +| `graylog_server__admin_user` | The main user account for the graylog administrator. Subkeys:<br> * `username`: Username<br> * `password`: Password<br> * `email`: Email<br> |
looks good besides this

2022-10-31 08:59 UTC, NavidSassan approved these changes

2022-10-31 09:59 UTC, merged